aws_region = "eu-central-1"
stack = "cloud-bootstrap"
aws_profile = "default"
source_repo_name = "cloud-bootstrap"
source_repo_main_branch_name = "main"
image_repo_name = "cloud-bootstrap"
container_name = "cloud-bootstrap"